Map: Nuke
PrivateLobby: FALSE
Private: FALSE
AllowedPlayers:
  -n0toh
  -chr1mz
  -rodcad66
  -pmahcgop
  -TheTobiasEaton
Hosts:
  -n0toh
  -pmahcgop
BannedPlayers:
  -callum09
RoundsPerHalf: 15
RoundsToWin: 16
RandomizeSide: TRUE
ExportStatsAtEnd: TRUE
ShutdownOnExit: TRUE
# TODO