Map: Nuke
PrivateLobby: FALSE
Private: FALSE
AllowedPlayers:
  -n0toh
  -Chr1mz
  -rodcad66
  -pmahCgoP
  -TheTobiasEaton
Host:
  -n0toh
  -pmahCgoP
BannedPlayers:
  -Callum09
RoundsPerHalf: 15
RoundsToWin: 16
ExportStatsAtEnd: TRUE
# TODO