name: SquadAssault
version: 1.0prealpha
main: com.podcrash.squadassault.Main
authors: [Noid, Notoh]
commands:
  quit:
    description: Leave a game.
    usage: /quit
  addalphaspawn:
    description: Adds a spawn of a map for alpha team.
    usage: /addalphaspawn
  addomegaspawn:
    description: Adds a spawn of a map for omega team.
    usage: /addomegaspawn
  creategame:
    description: starts creation of a game.
    usage: /damage <id> <mapname> <min players>
  deletegame:
    description: deletes a game.
    usage: /delete <id>
  enablemap:
    description: enables a map.
    usage: /enablemap <id>
  disablemap:
    description: disables a map.
    usage: /disablemap <id>
  finishcreation:
    description: finalizes the creation of a world.
    usage: /finishcreation
  addbomb:
    description: adds a bomb site to a map.
    usage: /addbomb <site_letter>
  reloadplugin:
    description: reloads the plugin
    usage: /reloadplugin
  setlobby:
    description: sets the lobby of a game.
    usage: /setlobby
  joingame:
    description: joins a game
    usage: /joingame <id>
  stopgame:
    description: stops all games
    usage: /stopgame
permissions:
  squadassault.admin:
    description: permission to use admin gamesetup/enable/disable/reload commands