name: SquadAssault
version: 1.0prealpha
main: com.podcrash.squadassault.Main
authors: [Noid, Notoh]
softdepend:
  - PowerNBT
commands:
#  quit:
#    description: Leave a game.
#    usage: /quit
#  addalphaspawn:
#    description: Adds a spawn of a map for alpha team.
#    usage: /addalphaspawn
#  addomegaspawn:
#    description: Adds a spawn of a map for omega team.
#    usage: /addomegaspawn
#  creategame:
#    description: starts creation of a game.
#    usage: /damage <id> <mapname> <min players>
#  deletegame:
#    description: deletes a game.
#    usage: /delete <id>
#  enablemap:
#    description: enables a map.
#    usage: /enablemap <id>
#  disablemap:
#    description: disables a map.
#    usage: /disablemap <id>
#  finishcreation:
#    description: finalizes the creation of a world.
#    usage: /finishcreation
#  addbomb:
#    description: adds a bomb site to a map.
#    usage: /addbomb <site_letter>
#  reloadplugin:
#    description: reloads the plugin
#    usage: /reloadplugin
#  setlobby:
#    description: sets the lobby of a game.
#    usage: /setlobby
#  joingame:
#    description: joins a game
#    usage: /joingame <id>
  stopgame:
    description: stops all games, server op only
    usage: /stopgame
#  listgames:
#    description: lists games on the server
#    usage: /listgames
#  announce:
#   description: announces
#    usage: /announce <message>
  advancedstats:
    description: gets a player's advanced stats
    usage: /advancedstats [player]
  setmaxplayers:
    description: sets max amount of players
    usage: /setmaxplayers <amount>
  setminplayers:
    description: sets min amount of players
    usage: /setminplayers <amount>
  setmap:
    description: sets the map
    usage: /setmap <map>
  setprivate:
    description: sets the lobby to be private or not
    usage: /setprivate <boolean>
  setrandomizeside:
    description: sets whether or not side is randomized on game start
    usage: /setrandomizeside <boolean>
  setroundshalf:
    description: sets the amount of rounds in the half
    usage: /setroundshalf <rounds>
  setroundswin:
    description: sets the amount of rounds to win
    usage: /setroundswin <rounds>
  setshutdown:
    description: sets whether or not the server shuts down on end
    usage: /setshutdown <boolean>
  whitelistplayer:
    description: whitelists a player so they can join a private lobby
    usage: /whitelistplayer <player>
  blacklistplayer:
    description: blacklists a player so they cannot join a lobby
    usage: /blacklistplayer <player>
  setexportstats:
    description: sets whether or not stats will be exported by the server on game end
    usage: /setexportstats <boolean>
  addhost:
    description: adds a player as host of the lobby
    usage: /addhost <player>
permissions:
  squadassault.admin:
    description: permission to use admin gamesetup/enable/disable/reload commands